env:
  browser: true
  es2021: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  comma-dangle: [0]
  indent: [2, tab]
  no-tabs: 0
  operator-linebreak: [2, after]
  semi: [1, always]
  no-unused-vars: [0]
  no-new-func: [0]
  require-jsdoc: [2, {
    require: {
      FunctionDeclaration: true,
      MethodDefinition: false,
      ClassDeclaration: true,
      ArrowFunctionExpression: false,
      FunctionExpression: false,
    }
  }]
  "space-before-function-paren": [ 2 , "never"]
  "@typescript-eslint/ban-ts-comment": 0
  "@typescript-eslint/no-explicit-any": 0
